### ISSUE TITLE
undefined method `server' for Arask::Railtie:Class (NoMethodError)

### ISSUE THREAD

**Issue by kumarpradeepf22** [Ebbe/arask#20] opened 2021-04-22 07:30 UTC
In the latest version 1.2.4, after running `bundle install` and restart the server, I am getting the below errors. After downgrading the version errors get resolved.

`gems/railties-5.2.5/lib/rails/railtie.rb:192:in `method_missing': undefined method `server' for Arask::Railtie:Class (NoMethodError)`

**Comment by Ebbe** [comment] 2021-04-26 07:32
Could be that I introduced a feature not supported in Rails 5. I'll look in to that.

**Comment by Ebbe** [comment] 2021-05-04 21:03
I released version 1.2.5 which should fix the problem. Thank you for taking the time to report the error!

**Comment by vitroz** [comment] 2021-05-06 12:37
@Ebbe , I got the same error using Rails 6, running version 1.2.5

**Comment by Ebbe** [comment] 2021-05-06 12:44
@vitroz Can you show a Gemfile that creates the error? I can run it with both Rails 5 and 6 now.

**Comment by vitroz** [comment] 2021-05-06 13:09
Thank you for your time @Ebbe 

My Gemfile
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.2.1'
gem 'sidekiq', '~> 6.1.1'
#gem 'whenever', require => false
gem 'arask', '1.2.5'
# issues when trying to use whenever on docker environment, using this alternative, using whenever is ideal.
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

gem "jwt"

gem "pagy", '~> 3.11.0'
gem 'oj', '3.3.9'
gem 'jbuilder', '~> 2.6', '>= 2.6.4'
```

This setup gives me the error described on the issue on start up, I changed to arask version 1.2.3 and got past that, but got a different error on sidekiq, but thats another story lol

**Comment by vitroz** [comment] 2021-05-06 14:37
version 1.2.3 is working fine for me by the way, I just had to rebuild my sidekiq container to have it be updated with arask 1.2.3

**Comment by Ebbe** [comment] 2021-05-07 13:47
Weird. That Gemfile works fine for me. How do you run rails?

**Comment by Ebbe** [comment] 2021-05-10 18:34
@vitroz me too. What command to run?

**Comment by Ebbe** [comment] 2021-07-19 08:58
I'll close this because I can't recreate it. Please make a step by step way to reproduce and reopen if needed.

**Closed by Ebbe** 2021-07-19 08:58 UTC
